version: '3'

services:

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    # volumes:
    #   - ~/apps/mssql/data:/var/lib/mssqlql/data
    volumes:
      - ./db-data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123qwe

  api:
    build:
      context: .
      dockerfile: ./AmerPay/Dockerfile
    # restart: always
    ports:
      - 9902:9902
    depends_on:
      - db
