version: '3'

services:

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 14333:1433
    volumes:
      - ./db-data/var/lib/mssqlql/data
    # volumes:
    #   - ./db-data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd

  api:
    build:
      context: .
      dockerfile: ./AmerPay/Dockerfile
    # restart: always
    ports:
      - 80:80
    depends_on:
      - db
